# -*- mode: python ; coding: utf-8 -*-
#
# PyInstaller spec file for QuickBench.app (macOS)
# Run with:  pyinstaller QuickBench.spec
#
# This spec bundles everything needed to run QuickBench as a native macOS
# .app — no Python installation, no terminal, no IDLE required.

import os

block_cipher = None

a = Analysis(
    ["QuickBench.py"],
    pathex=[],
    binaries=[],
    datas=[
        # Bundle the icon assets so _create_app_icon() can find them at runtime.
        # PyInstaller places them in the top-level of the .app Resources folder.
        ("QB.png", "."),
        ("QB.ico", "."),
    ],
    hiddenimports=[
        # psutil has platform-specific sub-modules that the static analyser
        # sometimes misses — list them explicitly to be safe.
        "psutil",
        "psutil._psmacosx",
        "psutil._psposix",
        "psutil._common",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="QuickBench",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,         # No terminal window — pure GUI app
    disable_windowed_traceback=False,
    argv_emulation=False,  # Must be False for tkinter on macOS
    target_arch=None,      # None = match the machine (arm64 on M-series, x86_64 on Intel)
    codesign_identity=None,
    entitlements_file=None,
    icon="QB.icns",        # The .icns is generated by build_mac.sh before this runs
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="QuickBench",
)

app = BUNDLE(
    coll,
    name="QuickBench.app",
    icon="QB.icns",
    bundle_identifier="com.quickbench.app",
    info_plist={
        # Display name shown in the Dock and Finder
        "CFBundleName":             "QuickBench",
        "CFBundleDisplayName":      "QuickBench",
        "CFBundleIdentifier":       "com.quickbench.app",
        "CFBundleVersion":          "3.0.0",
        "CFBundleShortVersionString":"3.0",

        # Tell macOS this is a GUI app and not to show it in the Dock
        # as a background agent
        "LSUIElement":              False,
        "LSBackgroundOnly":         False,

        # Minimum macOS version (12.0 = Monterey; covers M1/M2/M3/M4)
        "LSMinimumSystemVersion":   "12.0",

        # Required for Apple Silicon — supports both arm64 and x86_64
        "NSHighResolutionCapable":  True,

        # Suppress the "App is not optimized for your Mac" dialog
        # on Apple Silicon machines running an Intel build
        "NSPrincipalClass":         "NSApplication",

        # Privacy strings — required for macOS 13+ if the app accesses
        # certain hardware. QuickBench only reads CPU/RAM counters.
        "NSHumanReadableCopyright": "© 2025 QuickBench",
    },
)
